### ISSUE TITLE
Wat is dit?

### ISSUE THREAD

**Issue by KrijnHoetmer** [DikkeTimo/look-and-feel-corporate-identity#3]
Een link met een schuin element erin, met niks erin. Maar wat is het? :)

https://github.com/DikkeTimo/look-and-feel-corporate-identity/blob/bcbfa62eeb7f9586aa09b0b09cb7d1a9e9590035/ontwikkelaar.html#L128-L130

**Comment by TimOosterveer** [comment]
Een back to top button
